name: Schedule test

on:
  workflow_dispatch:
  schedule:
    - cron: "2-59/5 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Scheduled trigger test
        run: |
          echo "Schedule works"
          date -u
